### ISSUE TITLE
X-Plane 11: AI aircraft count resets to zero after disconnecting

### ISSUE THREAD

**Issue by oktal3700** [kuroneko/libxplanemp#13]
In X-Plane 11, I set the number of AI aircraft to one or more, then connect to VATSIM and disconnect again, the number of AI aircraft has reset to zero. Observed in XSB and swift. Also observed in XSB by another X-Plane.org forum user.

I wonder if something changed in the behaviour of the SDK function XPLMSetActiveAircraftCount, because I never saw this problem in X-Plane 10.

Maybe it's benign, in which case it would make sense to inhibit the warning that XSB generates about it.

**Comment by kuroneko** [comment]
This turned out to be a Laminar bug in 11 (Confirmed by Tyler).  It should be fixed in 11.02.
