### ISSUE TITLE
libxplanemp exhausts texture IDs

### ISSUE THREAD

**Issue by kuroneko** [kuroneko/libxplanemp#17]
A user has reported errors allocating texture IDs - this could be due to there not being a mechanism for X-Plane to reclaim spent texture IDs that are no longer required, and libxplanemp does not internally recycle unused texture IDs at this time.

**Comment by frungy2** [comment]
Was the user using the Flight Factor A320? For some reason that plane messes up the OpenGL stack, causing [this check](https://github.com/kuroneko/libxplanemp/blob/master/src/TexUtils.cpp#L299) to fail. That was the reason why I readded the glGetError() in my fork [here](https://github.com/frungy2/libxplanemp-xfs/commit/acb5d165d734c6dfd11336f2362df64dc5c41c0e).

On reading the #12 reasoning, maybe there should be no check after the call to XPLMGenerateTextureNumbers(...) and instead check if the texNum actually has a sane value?

**Comment by kuroneko** [comment]
The check within the OBJ7 rendering path was removed some time ago - we ran into problems with IXEG 733 on XP11 generating errors and Ben clarified that we shouldn't be bothering, and that resulted in the birth of the texture preflight check which simply verifies that what we're loading is sane.

**Comment by kuroneko** [comment]
ah, damn! except for that one.  that is a bug, and that explains the symptoms.
