### ISSUE TITLE
CSL aircrafts are not displayed in client with Vulkan rendering (X-Plane 11.50 public beta)

### ISSUE THREAD

**Issue by denispol** [kuroneko/libxplanemp#22]
This issue was reproduced in X-IVAP and Altitude for X-Plane (IVAO clients): since the release of public beta 11.50, CSL aircrafts are not displayed in clients when Vulkan rendering is enabled. It works however correctly with OpenGL rendering.

**Comment by kuroneko** [comment]
Not a bug.  Just plain, outright not supported in this tree (which I'm going to maintain for XP10 compatibility as long as practical).  See xsquawkbox/xplanemp2 for my legacy-free path forward.
